#!/usr/bin/env python3
# Copyright (c) 2017-2026 Dmitry Slobodchikov
# SPDX-License-Identifier: GPL-3.0-only

"""Convert local PEM server credentials into an ignored C header."""

from pathlib import Path


def array(name: str, value: bytes) -> str:
    encoded = ", ".join(f"0x{byte:02X}U" for byte in value + b"\0")
    return (
        f"static const unsigned char {name}[] = {{\n"
        f"  {encoded}\n"
        "};\n"
    )


private_directory = Path("TLS/Private")
certificate = (private_directory / "management_server.crt.pem").read_bytes()
private_key = (private_directory / "management_server.key.pem").read_bytes()
header = private_directory / "management_server_credentials.h"
header.write_text(
    """\
/**
  ******************************************************************************
  * @file           : management_server_credentials.h
  * @brief          : Generated management-server certificate and private key.
  * @project        : STM32F407 Health Check
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2017-2026 Dmitry Slobodchikov
  * All rights reserved.
  *
  * Generated by tools/embed_server_credentials.py. This ignored file may
  * contain a private key and must not be committed.
  *
  ******************************************************************************
  */

#ifndef MANAGEMENT_SERVER_CREDENTIALS_H
#define MANAGEMENT_SERVER_CREDENTIALS_H

"""
    + array("managementServerCertificate", certificate)
    + "\n"
    + array("managementServerPrivateKey", private_key)
    + "\n#endif /* MANAGEMENT_SERVER_CREDENTIALS_H */\n",
    encoding="utf-8",
)
header.chmod(0o600)
